
# IaC topic pipeline will deploy all topic into targetResourceGroup (topic resource group)
# Required variables to set:  projName, azureServiceConnection, azureLocation
# Required resources deployed by Master IaC and Shared IaC pipeline 
trigger: none

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:    
  # Comment out if defined at pipeline definition
  projName: '<project-name>' 
  azureServiceConnection: '<azureServiceConnectionName>'
  azLocation: 'westeurope'
  
  # Section - Topic deployment settings
  targetResourceGroup: '$(projName)-topic-$(topicName)'
  topicName: $[ format('{0}{1}', variables['Build.SourceBranchName'], variables['System.PullRequest.PullRequestId'] ) ]
  
  # Section - Master resource group and Keyvault reference
  masterKeyVault: 'master-$(projName)-kv'
  masterResourceGroup: '$(projName)-master'

  # Section - Master storage reference
  devopsStorageName: 'master$(projName)strg'
  devopsStorageContainerName: '$(projName)-devops'
  devopsBlobPrefix: '$(Build.DefinitionName)-$(Build.BuildNumber)'

  # Section - Shared resources reference
  sharedResourceGroup: '$(projName)-shared'
  sharedCosmosAccount: 'shared-$(projName)-cosmos'

  # Section - ARM artifact references
  topicIaCRepoPath: 'src/iac/topic'
  topicIaCArtifact: '$(projName)-topic-iac'

jobs:
- job: PrepIaC 
  displayName: Prepare topic resources
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: AzureCLI@2
    displayName: 'Create hash from branch name'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        topicHashCode=$(echo -n $(topicName) | md5sum | cut -c1-8)
        echo "topicHashCode=$topicHashCode"
        echo "##vso[task.setvariable variable=topicHashCode;isOutput=true]$topicHashCode"
    name: setTopicHashCode

  - task: AzureCLI@2
    displayName: 'Get Service Principal Object ID'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptLocation: inlineScript
      scriptType: bash
      inlineScript: |
        spName=$(az account show --output tsv --query user.name)
        spObjectId=$(az ad sp show --output tsv --query objectId --id $spName)
        echo "##vso[task.setvariable variable=spObjectId;isOutput=true]$spObjectId"
    name: setspObjectId   

- job: DeployIaC
  displayName: Deploy topic resources
  dependsOn: PrepIaC
  pool:
    vmImage: 'windows-latest'  # needed because of AzureFileCopy task
  variables:
    topicHashCode: $[ dependencies.PrepIaC.outputs['setTopicHashCode.topicHashCode'] ]
    spObjectId: $[ dependencies.PrepIaC.outputs['setspObjectId.spObjectId'] ]
  steps:

  - upload: $(topicIaCRepoPath)
    displayName: Publish IaC artifacts from repo
    artifact: $(topicIaCArtifact) 

  - download: current
    displayName: Get IaC artifacts
    artifact: $(topicIaCArtifact)
    patterns: '**/*' 

  - task: AzureFileCopy@4
    displayName: Copy ARM nested ARM templates to storage
    name: AzureFileCopy
    inputs:
      SourcePath: '$(Pipeline.Workspace)\$(topicIaCArtifact)\*'
      azureSubscription: '$(azureServiceConnection)'
      Destination: 'AzureBlob'
      storage: '$(devopsStorageName)'
      ContainerName: '$(devopsStorageContainerName)'
      sasTokenTimeOutInMinutes: '20'
      BlobPrefix: '$(devopsBlobPrefix)'
         
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment: Topic IaC'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      action: 'Create Or Update Resource Group'
      deploymentMode: 'Incremental'
      resourceGroupName: $(targetResourceGroup)
      location: '$(azLocation)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/$(topicIaCArtifact)/topic-deploy-environment.json'
      overrideParameters: '-projName $(projName) -location $(azLocation) -buildNumber $(devopsBlobPrefix) -buildArtifactsLocation $(AzureFileCopy.StorageContainerUri) -buildArtifactsLocationSASToken $(AzureFileCopy.StorageContainerSasToken) -spObjectId $(spObjectId) -hashTopicName $(topicHashCode)'
      deploymentOutputs: armoutputs

- job: Configure_shared_services_CosmosDB
  dependsOn: 
  - DeployIaC
  - PrepIaC
  displayName: Configure shared service CosmosDB
  pool: 
    vmImage: 'ubuntu-latest'
  variables:
    topicHashCode: $[ dependencies.PrepIaC.outputs['setTopicHashCode.topicHashCode'] ]
    databaseName: 'db-$(topicHashCode)'
    containerName: 'container-$(topicHashCode)'
    topicKeyVault: '$(projName)-$(topicHashCode)-kv'
  
  steps: 
  - task: AzureResourceGroupDeployment@2
    displayName: 'Azure Deployment: Topic IaC'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      action: 'Create Or Update Resource Group'
      deploymentMode: 'Incremental'
      resourceGroupName: $(sharedResourceGroup)
      location: '$(azLocation)'
      templateLocation: 'Linked artifact'
      csmFile: '$(topicIaCRepoPath)/deploy-cosmosdb-configuration.json'
      overrideParameters: '-accountName $(sharedCosmosAccount) -databaseName $(databaseName) -containerName $(containerName) -keyVaultName $(topicKeyVault) -topicResourceGroup $(targetResourceGroup)'